In [12]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([0, 0, 1,  ..., 1, 0, 1], dtype=torch.uint8)

In [13]:
db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [14]:
torch.cat((db[1:2],db[3:]))[0:5]

tensor([0, 0, 0, 1, 1], dtype=torch.uint8)

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],
            db[remove_index+1:]))

In [16]:
get_parallel_db(db,3)

tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_db = list()
  
  for i in range(len(db)):
    pds = get_parallel_db(db,i)
    parallel_db.append(pds)
    
  return parallel_db


In [18]:
pdbs = get_parallel_dbs(db)
pdbs

[tensor([0, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 1, 0

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [20]:
create_db_and_parallels(20)


(tensor([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 [tensor([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 0, 0, 0, 1

In [40]:
db,pdbs = create_db_and_parallels(5000)
db

tensor([0, 0, 0,  ..., 1, 0, 1], dtype=torch.uint8)

In [0]:
def query(db):
  return db.sum()

In [42]:
full_db_result = query(db)
full_db_result

tensor(2472)

In [0]:
sensitivity = 0
for pdb in pdbs:
  pdb_result = query(pdb)
  db_distance = torch.abs(pdb_result - full_db_result)   # L1 Sensitivity
  
  if(db_distance > sensitivity):
    sensitivity = db_distance

In [44]:
sensitivity

tensor(1)