In [1]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 0,  ..., 1, 0, 0], dtype=torch.uint8)

In [2]:
db = torch.rand(num_entries) > 0.5
db

tensor([0, 0, 0,  ..., 1, 1, 1], dtype=torch.uint8)

In [5]:
torch.cat((db[1:2],db[3:]))[0:5]

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],
            db[remove_index+1:]))

In [9]:
get_parallel_db(db,3)

tensor([0, 0, 0,  ..., 1, 1, 1], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_db = list()
  
  for i in range(len(db)):
    pds = get_parallel_db(db,i)
    parallel_db.append(pds)
    
  return parallel_db


In [14]:
pdbs = get_parallel_dbs()
pdbs

TypeError: ignored

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [16]:
create_db_and_parallels(20)


(tensor([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
        dtype=torch.uint8),
 [tensor([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
         dtype=torch.uint8),
  tensor([0, 0, 1, 1, 1, 0, 1