In [52]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([0, 1, 1,  ..., 1, 0, 1], dtype=torch.uint8)

In [53]:
db = torch.rand(num_entries) > 0.5
db

tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [54]:
torch.cat((db[1:2],db[3:]))[0:5]

tensor([0, 0, 0, 1, 1], dtype=torch.uint8)

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],
            db[remove_index+1:]))

In [56]:
get_parallel_db(db,3).shape

torch.Size([4999])

In [0]:
def get_parallel_dbs(db):
  parallel_db = list()
  
  for i in range(len(db)):
    pds = get_parallel_db(db,i)
    parallel_db.append(pds)
    
  return parallel_db


In [58]:
pdbs = get_parallel_dbs(db)
pdbs

[tensor([0, 1, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [60]:
create_db_and_parallels(20)


(tensor([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
        dtype=torch.uint8),
 [tensor([1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         dtype=torch.uint8),
  tensor([1, 1, 0, 0, 0, 1, 0

In [61]:
db,pdbs = create_db_and_parallels(5000)
db

tensor([1, 0, 1,  ..., 1, 0, 1], dtype=torch.uint8)

In [0]:
def query(db):
  return db.sum()

In [63]:
full_db_result = query(db)
full_db_result

tensor(2484)

In [0]:
sensitivity = 0
for pdb in pdbs:
  pdb_result = query(pdb)
  db_distance = torch.abs(pdb_result - full_db_result)   # L1 Sensitivity
  
  if(db_distance > sensitivity):
    sensitivity = db_distance

In [65]:
sensitivity

tensor(1)

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],db[remove_index+1:]))
  
def get_parallel_dbs(db):
  parallel_db = list()
  
  for i in range(len(db)):
    pds = get_parallel_db(db,i)
    parallel_db.append(pds)
    
  return parallel_db

def create_db_and_parallels(num_entries):
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db,pdbs

def query(db):
  return db.float().mean()

def sensitivity(query,num_entries):
  db,pdbs = create_db_and_parallels(num_entries)
  sensitive = 0
  
  full_db_result = query(db)
  
  for pdb in pdbs:
    db_distance = torch.abs(query(pdb) - full_db_result)
    
  if(db_distance > sensitive):
    sensitive = db_distance
    
  return sensitive
      
    

In [67]:
(sensitivity(query,1000))

tensor(0.0005)

In [0]:
def query(db,threshold =5):
  return (db.sum() > threshold).float()

 

In [69]:
for i in range(10):
  sens_f = sensitivity(query,num_entries = 10)
  print(sens_f)

0
0
0
0
0
0
tensor(1.)
0
tensor(1.)
0


In [70]:
db,_ = create_db_and_parallels(100)
db

tensor([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 1], dtype=torch.uint8)

In [71]:
pdb = get_parallel_db(db,remove_index=10)
pdb

tensor([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        1, 0, 1], dtype=torch.uint8)

In [72]:
db[10]

tensor(1, dtype=torch.uint8)

In [73]:
sum(db)

tensor(48, dtype=torch.uint8)

In [74]:
# Differencing attack using sum query
sum(db) - sum(pdb)

tensor(1, dtype=torch.uint8)

In [75]:
# Differencing attack using mean query
(sum(db).float()/len(db))-(sum(pdb).float()/len(pdb))

tensor(0.0053)

# **LESSON 5**

In [78]:
db , pdbs = create_db_and_parallels(100)
db


tensor([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0], dtype=torch.uint8)

In [0]:
first_flip_coin = (torch.rand(len(db)) > 0.5).float()
second_flip_coin = (torch.rand(len(db)) > 0.5).float()


In [83]:
first_flip_coin

tensor([1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
        1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1.,
        0., 0., 1., 0., 0., 1., 1., 1., 0., 0.])

In [85]:
second_flip_coin

tensor([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
        0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1.,
        0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0.,
        1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        0., 1., 1., 0., 1., 1., 1., 1., 1., 0.])

In [0]:
augmented_database = db.float() * first_flip_coin + (1 - first_flip_coin) * second_flip_coin

In [92]:
torch.mean(augmented_database.float())
torch.mean(second_flip_coin.float())

tensor(0.5300)

In [89]:
torch.mean(db.float())

tensor(0.5400)

In [0]:
db_result = torch.mean(augmented_database.float()) * 2 -0.5

In [0]:
def query(db):
  true_result = torch.mean(db.float())
  first_flip_coin = (torch.rand(len(db))).float()
  second_flip_coin = (torch.rand(len(db))).float()
  
  augmented_database = db.float() * first_flip_coin + (1 - first_flip_coin) * second_flip_coin
  db_result = torch.mean(augmented_database.float()) * 2 -0.5
  return db_result,true_result

In [96]:
db,pds = create_db_and_parallels(100)
private_result,true_result = query(db)
print("With Noise: ",private_result)
print("Without Noise: ",true_result)

With Noise:  tensor(0.6744)
Without Noise:  tensor(0.6100)


In [97]:
db,pds = create_db_and_parallels(1000)
private_result,true_result = query(db)
print("With Noise: ",private_result)
print("Without Noise: ",true_result)

With Noise:  tensor(0.4651)
Without Noise:  tensor(0.4810)


In [98]:
db,pds = create_db_and_parallels(10000)
private_result,true_result = query(db)
print("With Noise: ",private_result)
print("Without Noise: ",true_result)

With Noise:  tensor(0.5071)
Without Noise:  tensor(0.5029)
